In [1]:
import pandas as pd
import numpy as np
import matplotlib as mpl

In [16]:
sequencia = [1,2,3,4,5,6]

In [17]:
sequencia = np.array(sequencia)

In [14]:
sequencia+10
sequencia*10

array([10, 20, 30, 40, 50, 60])

In [21]:
sequencia2 = np.array([sequencia,sequencia*2,sequencia*3])
sequencia2 #cada linha é dada depois da vírgula

array([[ 1,  2,  3,  4,  5,  6],
       [ 2,  4,  6,  8, 10, 12],
       [ 3,  6,  9, 12, 15, 18]])

In [22]:
#Funções np.(linspace, logspace, arange, zeros, ones, empty, identity) para criação

In [25]:
a = sequencia2.reshape(6,3)
a

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 2,  4,  6],
       [ 8, 10, 12],
       [ 3,  6,  9],
       [12, 15, 18]])

In [29]:
b = a[a%3 == 0]
b

array([ 3,  6,  6, 12,  3,  6,  9, 12, 15, 18])